# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, releases/** ]
  pull_request:
    branches: [ master, releases/** ]

jobs:
  build:
    name: Build and test on JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ 8, 11, 17, 21 ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml --no-transfer-progress
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
